var doTheThing, root;

root = typeof exports !== "undefined" && exports !== null ? exports : this;

doTheThing = root.doTheThing = function(source) {
    var loading = d3.select('.loading');

    loading.transition()
        .duration(200)
        .style('opacity', '1')
        .style('visibility', function(d) {
            return 'visible';
        });


    return $.getJSON(source).done(function(data) {
        var details, sdata;

        loading.transition()
            .duration(1000)
            .style('opacity', '0')
            .delay(500)
            .remove();
        
        var topics = _(data);
        var item_id_counter = 0;
        
        topics = topics.map(function(d) {
            return {
                id: item_id_counter++,
                value: d.enfase,
                author: d.autor,
                situacao: '-',
                sexo: '-',
                url: 'http://www.camara.leg.br/internet/Deputado/dep_Detalhe.asp?id=' + d.ideCadastro,
                email: '-',
                foto: 'http://www.camara.leg.br/internet/deputado/bandep/' + d.ideCadastro + '.jpg',
                uf: d.uf,
                partido: d.partido,
                topico: d.tag
            };
        });
        
        topics = topics.compact();

        topics = topics.groupBy(function(d) {
            return d.topico;
        });

        item_id_counter = 0;
        topics = topics.pairs().map(function(pair) {
            var topic = pair[0];
            var enfases = pair[1];
            return {
                id: item_id_counter++,
                topic: topic,
                value: d3.sum(enfases, function(d) { return d.value; }),
                children: enfases
            };
        });
        
        topics = topics.value();
        
        details = null;
        if (!data.description) {
            details = data.title;
        } else {
            sdata = {
                topic_count: topics.length
            };
            details = sprintf(data.description, sdata);
        }
        d3.select('.intro .detail').text(details);
        return d3.custom.forceLayout(topics);
    });
};

// ---
// generated by coffee-script 1.9.2
